import { ComponentSpec } from "./types";

// Component Library – sane-ish defaults (feel free to tune)
export const COMPONENT_LIBRARY: ComponentSpec[] = [
  {
    kind: "Web",
    label: "Client",
    baseLatencyMs: 10,
    capacityRps: 20000,
    failureRate: 0.0001,
    costPerHour: 0,
  },
  {
    kind: "CDN",
    label: "CDN",
    baseLatencyMs: 20,
    capacityRps: 50000,
    failureRate: 0.0005,
    costPerHour: 0.5,
  },
  {
    kind: "API Gateway",
    label: "API Gateway",
    baseLatencyMs: 8,
    capacityRps: 8000,
    failureRate: 0.001,
    costPerHour: 0.15,
  },
  {
    kind: "Load Balancer",
    label: "Load Balancer",
    baseLatencyMs: 3,
    capacityRps: 100000,
    failureRate: 0.0005,
    costPerHour: 0.08,
  },
  {
    kind: "Service",
    label: "Service",
    baseLatencyMs: 12,
    capacityRps: 3000,
    failureRate: 0.002,
    costPerHour: 0.2,
  },
  {
    kind: "Cache (Redis)",
    label: "Cache (Redis)",
    baseLatencyMs: 1,
    capacityRps: 15000,
    failureRate: 0.0015,
    costPerHour: 0.12,
  },
  {
    kind: "DB (Postgres)",
    label: "DB (Postgres)",
    baseLatencyMs: 4,
    capacityRps: 1200,
    failureRate: 0.001,
    costPerHour: 0.35,
  },
  {
    kind: "Object Store (S3)",
    label: "Object Store (S3)",
    baseLatencyMs: 35,
    capacityRps: 5000,
    failureRate: 0.0008,
    costPerHour: 0.25,
  },
  {
    kind: "Message Queue (Kafka Topic)",
    label: "Kafka Topic",
    baseLatencyMs: 5,
    capacityRps: 20000,
    failureRate: 0.001,
    costPerHour: 0.18,
  },
  // New components from Appendix 1
  {
    kind: "Search Index (Elastic)",
    label: "Search Index",
    baseLatencyMs: 15,
    capacityRps: 6000,
    failureRate: 0.0015,
    costPerHour: 0.3,
  },
  {
    kind: "Read Replica",
    label: "Read Replica",
    baseLatencyMs: 6,
    capacityRps: 1500,
    failureRate: 0.001,
    costPerHour: 0.25,
  },
  {
    kind: "Object Cache (Memcached)",
    label: "Memcached",
    baseLatencyMs: 1,
    capacityRps: 20000,
    failureRate: 0.0015,
    costPerHour: 0.12,
  },
  {
    kind: "Auth",
    label: "Auth Service",
    baseLatencyMs: 10,
    capacityRps: 4000,
    failureRate: 0.002,
    costPerHour: 0.2,
  },
  {
    kind: "Rate Limiter",
    label: "Rate Limiter",
    baseLatencyMs: 2,
    capacityRps: 15000,
    failureRate: 0.001,
    costPerHour: 0.15,
  },
  {
    kind: "Stream Processor (Flink)",
    label: "Stream Processor",
    baseLatencyMs: 25,
    capacityRps: 5000,
    failureRate: 0.002,
    costPerHour: 0.4,
  },
  {
    kind: "Worker Pool",
    label: "Worker",
    baseLatencyMs: 12,
    capacityRps: 3000,
    failureRate: 0.002,
    costPerHour: 0.2,
  },
  {
    kind: "ID Generator (Snowflake)",
    label: "ID Generator",
    baseLatencyMs: 1,
    capacityRps: 50000,
    failureRate: 0.0005,
    costPerHour: 0.15,
  },
  {
    kind: "Shard Router",
    label: "Shard Router",
    baseLatencyMs: 2,
    capacityRps: 100000,
    failureRate: 0.0005,
    costPerHour: 0.08,
  },
  {
    kind: "Tracing/Logging",
    label: "Telemetry",
    baseLatencyMs: 3,
    capacityRps: 40000,
    failureRate: 0.0008,
    costPerHour: 0.1,
  },
  {
    kind: "Edge Function",
    label: "Edge Function",
    baseLatencyMs: 8,
    capacityRps: 8000,
    failureRate: 0.002,
    costPerHour: 0.18,
  },
  {
    kind: "Origin Shield (CDN Proxy)",
    label: "CDN Origin Shield",
    baseLatencyMs: 4,
    capacityRps: 50000,
    failureRate: 0.0008,
    costPerHour: 0.18,
  },
];
